---
theme: dark

identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_JWT_SECRET}

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

authentication_backend:
  ldap:
    address: ldap://lldap:3890
    base_dn: dc=gawley,dc=net
    attributes:
      username: uid
      mail: mail
      display_name: displayName
      group_name: cn
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    user: uid=admin,ou=people,dc=gawley,dc=net

session:
  secret: ${AUTHELIA_SESSION_SECRET}
  expiration: 3600
  inactivity: 300
  cookies:
    - domain: gawley.net
      authelia_url: https://auth.gawley.net
      default_redirection_url: https://home.gawley.net

storage:
  encryption_key: ${AUTHELIA_ENCRYPTION_KEY}
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: one_factor
  rules:
    - domain: vault.gawley.net
      policy: two_factor
      subject: "group:admins"
    - domain: grafana.gawley.net
      policy: two_factor
      subject: "group:admins"