- Family:
    - Mail:
        href: http://mail.gawley.net
        icon: roundcube.png
        description: Family Email
    - Chat:
        href: http://chat.gawley.net
        icon: xmpp.png
        description: Family Chat
    - Photos:
        href: http://photos.gawley.net
        icon: immich.png
        description: Family Photos
    - Passwords:
        href: http://vault.gawley.net
        icon: bitwarden.png
        description: Password Manager
- Admin:
    - Grafana:
        href: http://grafana.gawley.net
        icon: grafana.png
        description: Monitoring