[global]
   workgroup = GAWLEYCORP
   server string = Gawleycorp File Server
   security = user
   passdb backend = tdbsam

[gawleycorp]
   path = /shares/gawleycorp
   valid users = @gawleycorp
   read only = no
   browseable = yes